### ISSUE TITLE
Support raspberry pi build

### ISSUE THREAD

**Issue by opensource21** [simplex-chat/simplex-chat#1273]
I wonder if it could be possible that the dockerfile based on debian stable and the haskell-version of the packetmanagment.
Currently, the build with the dockerfile fails, because the haskell-version is too old. It's difficult to get the newest haskell-version for arm. So if you use your own dockerfile for build and let it based on a regular debian-image it should be easy for everyone to compile the version.
The main drawback I see at the moment you can't use the newest haskell version. Furthermore, the automatic build should  be based on the dockerfile.

**Comment by shumvgolove** [comment]
This should be fixed. Please reopen if it doesn't.

**Comment by opensource21** [comment]
Thanks, unfortunately it's still not working:

```
[+] Building 134.0s (8/16)                                                                                                                        
 => [internal] load build definition from Dockerfile                                                                                         0.1s
 => => transferring dockerfile: 836B                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                            0.0s
 => => transferring context: 2B                                                                                                              0.0s
 => [internal] load metadata for docker.io/library/ubuntu:focal                                                                              1.7s
 => [build  1/11] FROM docker.io/library/ubuntu:focal@sha256:450e066588f42ebe1551f3b1a535034b6aa46cd936fe7f2c6b0d72997ec61dbd               26.4s
 => => resolve docker.io/library/ubuntu:focal@sha256:450e066588f42ebe1551f3b1a535034b6aa46cd936fe7f2c6b0d72997ec61dbd                        0.0s
 => => sha256:450e066588f42ebe1551f3b1a535034b6aa46cd936fe7f2c6b0d72997ec61dbd 1.42kB / 1.42kB                                               0.0s
 => => sha256:347107c9cb897fb2f88d65bc83b395b3980509ad266e9c63a35df930adda22f5 529B / 529B                                                   0.0s
 => => sha256:7213448eab55fe4ef8b0035877e54c3e2d68fe42768a73b9a8ea18690c5ab4c2 1.48kB / 1.48kB                                               0.0s
 => => sha256:88411d40226eb74e038e5d2cbedefbd7555c34298ed687d1073cf87740fab694 24.59MB / 24.59MB                                            10.8s
 => => extracting sha256:88411d40226eb74e038e5d2cbedefbd7555c34298ed687d1073cf87740fab694                                                   14.4s
 => [internal] load build context                                                                                                           53.3s
 => => transferring context: 162.52MB                                                                                                       53.2s
 => [build  2/11] RUN apt-get update && apt-get install -y curl git build-essential libgmp3-dev zlib1g-dev libssl-dev                      103.1s
 => [build  3/11] RUN a=$(arch); curl https://downloads.haskell.org/~ghcup/$a-linux-ghcup -o /usr/bin/ghcup &&     chmod +x /usr/bin/ghcup   1.4s
 => ERROR [build  4/11] RUN ghcup install ghc 8.10.7                                                                                         1.0s 
------                                                                                                                                            
 > [build  4/11] RUN ghcup install ghc 8.10.7:                                                                                                    
#7 0.874 /usr/bin/ghcup: 1: cannot open html: No such file                                                                                        
#7 0.874 /usr/bin/ghcup: 2: Syntax error: redirection unexpected                                                                                  
------
executor failed running [/bin/sh -c ghcup install ghc 8.10.7]: exit code: 2
```
`ghcup install ghc 8.10.7` seems to have a problem.

@shumvgolove Can't reopen the issue. I hope you see the message.

**Comment by shumvgolove** [comment]
@opensource21 

What's your host machine `arch` ?

**Comment by shumvgolove** [comment]
Unfortunately, I can't test this setup due to the lack of hardware, and it seems that `ghcup`/`ghc` has limited support for `armv7`.

See:
- [ghcup – Supported platforms](https://www.haskell.org/ghcup/install/#supported-platforms)
- [ghcup – GHCup fails to install on armv7](https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/405)

One potential solution to this (although quite brutal) is to switch your RPi distro to `aarch64` architecture.

**Comment by opensource21** [comment]
Okay I will try it with the next update. Seems a good idea to change to 64bit. Unfortunately I'm not sure if I can test it this year. Feel free to close it.
