### ISSUE TITLE
[Bug]: Couldn't set database passphrase

### ISSUE THREAD

**Issue by jeremyredhead** [simplex-chat/simplex-chat#5377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Windows

### OS version

Windows 10 22H2

### App version

IDK, Latest (just downloaded it)

### Current Behavior

Tried to setup a profile (first time using this app), typed in a database passphrase, in both inputs, the first input kept showing a red exclamation icon, and the "Set database passphrase" button was greyed out & unclickable. (and, *yes*, the inputs were matching, I checked)

Tried restarting the app (which chucked me to the same screen -- bad design!!), deleted `%AppData%/SimpleX`, same thing, gave up and selected "use random passphrase".

### Expected Behavior

It should allow setting a passphrase LOL

### Steps To Reproduce

1. Install on Windows 10?
2. Make a profile
3. Type in database passphrase in both inputs
4. Try to click "Set database passphrase" button

**Comment by jeremyredhead** [comment]
I was indeed typing a passphrase with spaces in it, as usually 
passphrases include spaces.

So either
a) "It" (whatever exact component that may be) should be fixed to allow 
spaces or,
b) If that is somehow impossible or inexplicably undesirable, then the 
UI/UX should be improved to actually indicate the problem with the 
passphrase, or at least list what characters are allowed.

**Comment by JDgroover** [comment]
This issue still exists.

Please either
a) allow spaces to be used as a part of passphrases, or
b) make some indication in UI/UX to explain the requirements, or the error. This could occur a step before passphrase is entered (eg. "passphrases can contain any characters *except* the naughty space character!"), or, an error message if the user unknowingly transgresses this previously unexplained rule. (e.g. 'you tried to enter a passphrase with the naughty space character, you must not do this, now do it right, even though we didn't tell you before!") ;-) ... or similar.

Thank you for considering this improvement.
