### ISSUE TITLE
[Bug]: iOS v6.3.4 : cannot create new group (app freeze)

### ISSUE THREAD

**Issue by BarbossHack** [simplex-chat/simplex-chat#5906]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Platform

iOS

### OS version

iOS 18.5

### App version

6.3.4

### Current Behavior

When attempting to create a new group in the iOS app, the app freezes as soon as I click the 'Create Group' button. I have to force quit the app, and the group is not created.

> Screenshot showing the frozen screen:

![Image](https://github.com/user-attachments/assets/d12cfbc7-d306-492b-ac40-db265df02cb3)

### Expected Behavior

The app is not expected to freeze in this scenario.

### Steps To Reproduce

1. Open the app
2. Click on `write` logo
3. Click on `Create group`
4. Enter a group name
5. Click on `Create group`
6. Freeze

### Relevant log output

```shell

```

**Comment by kyle-blair** [comment]
I can confirm this happens to me as well. After filling in the group info and clicking create nothing happens and the app freezes. The group is not created. I have to force quit the app and reopen it.

**Comment by BarbossHack** [comment]
This was fixed in today's update

**Comment by aldaw** [comment]
Still encountering this bug. Even with newest version on iOS Version 6.3.6 (Build 282)

Edit: I noticed now when I click on next on the iOS keyboard it works. But when I klick on the blue text within the app „Create Group“ it gets stuck.
