### ISSUE TITLE
Can't remove contact that has a pending group invite

### ISSUE THREAD

**Issue by neutralinsomniac** [simplex-chat/simplex-chat#860]
I added a contact, then invited that contact to a group. The contact never accepted the group invite. I then went to delete the contact, but received the error that the contact is still in the group. I then removed the contact from the group (even though they aren't listed in the member list), and the app said the contact was removed. I can do this any number of times and still receive the same "contact was removed" message. Despite this, I still can't delete the contact as the app still thinks it's in the group.

**Comment by epoberezkin** [comment]
Thanks - we are just in the process of stabilising the groups for the release of mobile UI - I assume it's in the terminal app?

**Comment by neutralinsomniac** [comment]
It is in the terminal app yes. Here is the output if it helps at all:

```
> [jeremy@x ~]$ simplex-chat -c
SimpleX Chat v3.1.0
db: /home/jeremy/.simplex/simplex_v1_chat.db, /home/jeremy/.simplex/simplex_v1_agent.db
use -x CLI option to connect via SOCKS5 at :9050
type "/help" or "/h" for usage info
Current user: neutral-x1
3 contacts connected (use /cs for the list)
Your address is active! To show: /sa
#mnt member neutral-4a error: ChatErrorAgent {agentError = CONN {connErr = NOT_FOUND}}
#mnt: connected to server(s)
1 group member errors (run with -c option to show each error)
/delete neutral-4a
neutral-4a: contact cannot be deleted, it is a member of the group(s) #mnt
/remove #mnt neutral-4a
#mnt: you removed neutral-4a from the group
/remove #mnt neutral-4a
#mnt: you removed neutral-4a from the group
/delete neutral-4a
neutral-4a: contact cannot be deleted, it is a member of the group(s) #mnt
>  
```

**Comment by epoberezkin** [comment]
Thank you!

**Comment by epoberezkin** [comment]
fixed in master branch, will be in 3.1 release

**Comment by neutralinsomniac** [comment]
I just recompiled from master, and I still can't fully remove these members from the group. Could this be because my database is in an odd state now or something?

**Comment by neutralinsomniac** [comment]
`member_status` in the `group_members` table is `removed`

**Comment by epoberezkin** [comment]
Yes, it would only work if you remove the member with the fixed code...

Currently you can either remove the member from the database or delete the whole group.

Also, it still want work if the contact would join the group and then leave or be deleted from the group - it is not possible to delete the contact until the group is deleted. This will be fixed later.

**Comment by neutralinsomniac** [comment]
Alright. It's nice that the schema is simple enough to allow for the removal. :) Thanks!

**Comment by epoberezkin** [comment]
not all tables are simple, and I should have told you to enable foreign keys - sqlite has them off by default... Some deletions can trigger cascade deletions, so be careful. There is a doc about the schema too, it might help :)
